package controller;

/**
 * Enumerates actions which can be called on by the user as they interact with the user interface.
 * 
 * @author John Coleman
 *
 */
public enum Action {
  ECHO, DELETE_NODE, NEW_NODE, FETCH_NODE_DATA, SET_NODE_DATA, SET_ALL_PIPE_DATA, NEW_PIPE, FETCH_PIPE_DATA, SET_PIPE_DATA, DELETE_PIPE, VOLUMES_CALC, PRESSURES_CALC, PIPE_SIZES_CALC, EFFICIENCY_CALC, LIST_PRESSURE_EQUATIONS, MODE_SELECTION, FETCH_MODE_DATA, NEW_FILE, CLONE_FILE, OPEN_FILE, IMPORT_CSV, EXPORT_CSV, CLOSE_FILE, SAVE_FILE, SAVE_FILE_AS, SAVE_ALL_FILES, EXIT_ALL, NEXT_GRAPH, PREV_GRAPH, ADD_GRAPH, MOVE_GRAPH, VOLUMES_AND_PRESSURES_CALC, PRESSURES_AND_EFFICIENCIES_CALC
}
